version: "3.9"

services:
  psono-database:
    image: postgres:15-alpine
    container_name: psono-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /opt/docker/psono/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
